/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "bldai-primary-background": "#f9fbfe",
        "bldai-monochrome-blue-grey-300": "#e4e7eb",
        "bldai-text-primary": "#253858",
        "bldai-text-secondary": "#5c6983",
        "bldai-primary-main": "#5c55b8",
        "bldai-monochrome-grey-300": "#e0e0e0",
        "bldai-text-light-contrast": "#fff",
        "text-secondary": "rgba(66, 82, 110, 0.86)",
        "bldai-interface-other-activerating": "#ffb400",
        "bldai-monochrome-blue-grey-700": "#66788a",
        "bldai-monochrome-blue-grey-600": "#7b8b9a",
        "bldai-monochrome-blue-grey-500": "#a6b1bb",
        "bldai-monochrome-blue-grey-400": "#c7ced4",
        "bldai-monochrome-blue-grey-200": "#edf0f2",
        "bldai-monochrome-blue-grey-100": "#f4f5f7",
        "bldai-monochrome-grey-850": "#323232",
        "bldai-monochrome-grey-800": "#424242",
        "bldai-monochrome-grey-700": "#616161",
        "bldai-monochrome-grey-600": "#757575",
        "bldai-monochrome-grey-500": "#9e9e9e",
        "bldai-monochrome-grey-450": "#b9babc",
        "bldai-monochrome-grey-400": "#bfc1c3",
        "bldai-monochrome-grey-350": "#dbdcdf",
        "bldai-monochrome-grey-200": "#eee",
        "bldai-monochrome-grey-100": "#f5f5f5",
        "success-main": "#00c871",
        "bldai-text-dark-contrast": "#212121",
        "bldai-text-disabled": "#9a9c9d",
        gray: "rgba(0, 0, 0, 0.2)",
        "bldai-interface-success-background": "#edf7ed",
        "bldai-interface-success-dark-text": "#1e4620",
        "bldai-interface-success-light": "#a1dca3",
        "bldai-interface-success-dark": "#00605c",
        "bldai-interface-warning-background": "#fff5e5",
        "bldai-interface-warning-dark-text": "#664000",
        "bldai-interface-warning-light": "#ffe9b4",
        "bldai-interface-warning-dark": "#b76600",
        "bldai-interface-warning-main": "#ffa100",
        "bldai-interface-error-background": "#fae8e8",
        "bldai-interface-error-dark-text": "#520a0c",
        "bldai-interface-error-light": "#fcdfd0",
        "bldai-interface-error-dark": "#940d27",
        "bldai-interface-error-main": "#ce1a1d",
        "bldai-interface-info-background": "#eceefd",
        "bldai-interface-info-dark-text": "#1a245f",
        "bldai-interface-info-light": "#d9e0fe",
        "bldai-interface-info-dark": "#0c1471",
        "bldai-interface-info-main": "#4259ed",
        "bldai-secondary-border": "#d6d5f3",
        "bldai-secondary-main": "#b3afe9",
        "bldai-secondary-light": "#c2bfed",
        "bldai-secondary-dark": "#7d7aa3",
        "bldai-secondary-background": "#f3f5fd",
        "bldai-primary-border": "#aba8db",
        "bldai-primary-light": "#dcdbf9",
        "bldai-primary-dark": "#403b80",
      },
      spacing: {},
      fontFamily: {
        "bldai-special-overline": "Poppins",
        "bldai-special-monospace": "'Anonymous Pro'",
      },
      borderRadius: {
        "2xl-3": "21.3px",
      },
    },
    fontSize: {
      "11xl": "1.88rem",
      "29xl": "3rem",
      "37xl": "3.5rem",
      mini: "0.94rem",
      "41xl": "3.75rem",
      "5xl": "1.5rem",
      "101xl": "7.5rem",
      xs: "0.75rem",
      "17xl": "2.25rem",
      sm: "0.88rem",
      base: "1rem",
      xl: "1.25rem",
      lg: "1.13rem",
      "13xl": "2rem",
      "lg-7": "1.17rem",
      inherit: "inherit",
    },
    screens: {
      lg: {
        max: "1200px",
      },
      md: {
        max: "960px",
      },
      sm: {
        max: "420px",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
